### ISSUE TITLE
blockmedian [ERROR]: Option -C: Cannot be combined with -G

### ISSUE THREAD

**Issue by Han-Su22** [PIK-LPJmL/LandInG#7]
When running the elevation file to resample data using GMT, I got the error:
blockmedian [ERROR]: Option -C: Cannot be combined with -G

It seems that the latest version of GMT doesn't allow option -G and -C to appear simultaneously. See -G:
https://docs.generic-mapping-tools.org/6.5/blockmedian.html#index-0

Since it's a bit complicated for me to install GMT=6.1.1, I removed "-C" in the code. Then, I can run the code. Is this the correct solution?

**Comment by sostberg** [comment]
Going by the GMT documentation, this was changed in GMT version 6.3. I ran a quick test with version 6.1.1 and  left out the `-C` in the call. The result appears to be identical to the one including `-C` so I guess it should be fine to simply leave out `-C`.

**Comment by sostberg** [comment]
This has been changed in the update to LandInG version 1.1.0, see 268018b591d9bcdd5bd8645a5079f178477db559
